apiVersion: v1
kind: ConfigMap
metadata:
  name: mechmanager-execution-config
  namespace: mechmanager-execution
data:
  APP_NAME: mechmanager-execution
  APP_ENV: production
  PORT: "8080"
  GIN_MODE: "release"

  DB_HOST: "execution-db.csrmunroi7us.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: meu_usuario
  DB_NAME: mechmanager_execution

  AWS_REGION: us-east-1

  # Tabela DynamoDB para fila de execução em tempo real
  DYNAMO_EXECUTION_TABLE: execution-queue

  # Fila SQS de entrada: OS Service publica aqui quando uma OS é aceita
  SQS_EXECUTION_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/975050103410/execution-queue

  # Fila SQS de saída: este serviço publica quando a execução é concluída/falha
  SQS_EXECUTION_COMPLETE_URL: https://sqs.us-east-1.amazonaws.com/975050103410/execution-complete

  CORS_ALLOW_ORIGINS: "http://localhost,http://localhost:3000"

  NEW_RELIC_APP_NAME: mechmanager-execution
  NEW_RELIC_LICENSE_KEY: "7a9a4bcf25026be63ca7d2f0dc7d2f448bf7NRAL"
