apiVersion: v1
kind: Secret
metadata:
  name: mechmanager-execution-secrets
  namespace: mechmanager-execution
type: Opaque
stringData:
  DB_PASS: minha_senha
  AWS_ACCESS_KEY_ID: CHANGE_ME
  AWS_SECRET_ACCESS_KEY: CHANGE_ME
  AWS_SESSION_TOKEN: CHANGE_ME
