apiVersion: v1
kind: Service
metadata:
  name: mechmanager-execution-api-lb
  namespace: mechmanager-execution
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: mechmanager-execution
    component: api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
