name: Atualizar Configurações K8s

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: mechmanager-execution
  NAMESPACE: mechmanager-execution

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar kubectl
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Aplicar ConfigMap e Secrets
        run: |
          kubectl apply -f k8s/configmap.yaml -n $NAMESPACE
          kubectl apply -f k8s/hpa.yaml -n $NAMESPACE
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/secrets.yaml -n $NAMESPACE

      - name: Reiniciar Deployment para aplicar configs
        run: |
          kubectl rollout restart deployment/mechmanager-execution-api -n $NAMESPACE
          kubectl rollout status deployment/mechmanager-execution-api -n $NAMESPACE --timeout=180s
